"""add agent wallet to whitelist

Revision ID: 02796e97c639
Revises: cc6dc41723f8
Create Date: 2026-03-07 06:35:27.799016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02796e97c639'
down_revision: Union[str, None] = 'cc6dc41723f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal_whitelists', 'agent_wallet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal_whitelists', 'agent_wallet',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
