"""add balance data

Revision ID: 075c7bb5ee0c
Revises: 4262f0cfefa0
Create Date: 2026-03-09 13:30:57.506678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075c7bb5ee0c'
down_revision: Union[str, None] = '4262f0cfefa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('bnb_balance', sa.Numeric(), nullable=True),
    sa.Column('token_value', sa.Numeric(), nullable=True),
    sa.Column('total_value', sa.Numeric(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=True),
    sa.Column('total_pnl', sa.Numeric(), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_holdings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('avg_price', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=True),
    sa.Column('amount_token', sa.Numeric(), nullable=True),
    sa.Column('amount_bnb', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_history')
    op.drop_table('token_holdings')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
