"""add beneficiary_address on proposal

Revision ID: 0aa81ab3bd6d
Revises: 687fb0df9aa2
Create Date: 2026-03-04 13:25:13.101434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa81ab3bd6d'
down_revision: Union[str, None] = '687fb0df9aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
