"""fix whitelist unique constraint

Revision ID: 0ee05c2fcc67
Revises: a6cfadbc4e33
Create Date: 2026-03-08 04:55:50.804471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee05c2fcc67'
down_revision: Union[str, None] = 'a6cfadbc4e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
