"""fix whitelist unique constraint

Revision ID: 1896fdeb2be1
Revises: 0ee05c2fcc67
Create Date: 2026-03-08 05:11:57.603906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1896fdeb2be1'
down_revision: Union[str, None] = '0ee05c2fcc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
