"""add presale table

Revision ID: 1a6a6e8cce1b
Revises: 3d6bb6bec2a5
Create Date: 2026-03-05 10:11:14.590913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6a6e8cce1b'
down_revision: Union[str, None] = '3d6bb6bec2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_buy_bnb', sa.Float(), nullable=False),
    sa.Column('max_buy_bnb', sa.Float(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=True),
    sa.Column('sale_proxy_contract', sa.String(), nullable=True),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presales')
    # ### end Alembic commands ###
