"""fix agent_id type c

Revision ID: 2aa3c48d10fc
Revises: 6f7cb08fb265
Create Date: 2026-03-09 16:41:22.599220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa3c48d10fc'
down_revision: Union[str, None] = '6f7cb08fb265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
