"""add beneficiary_address on proposal

Revision ID: 3d6bb6bec2a5
Revises: 0aa81ab3bd6d
Create Date: 2026-03-04 13:48:28.208821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6bb6bec2a5'
down_revision: Union[str, None] = '0aa81ab3bd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('meta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'meta')
    # ### end Alembic commands ###
