"""add emergency cancel

Revision ID: 5dfa7ecbd47f
Revises: dda7c8c38ca4
Create Date: 2026-03-10 18:45:09.696965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfa7ecbd47f'
down_revision: Union[str, None] = 'dda7c8c38ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
