"""add beneficiary_address on proposal

Revision ID: 687fb0df9aa2
Revises: 4374ddeb0adf
Create Date: 2026-03-04 13:19:54.294780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687fb0df9aa2'
down_revision: Union[str, None] = '4374ddeb0adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('beneficiary_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'beneficiary_address')
    # ### end Alembic commands ###
