"""fix agent_id type b

Revision ID: 6f7cb08fb265
Revises: b8da6a4cf3f9
Create Date: 2026-03-09 16:28:12.091940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7cb08fb265'
down_revision: Union[str, None] = 'b8da6a4cf3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
