"""fix whitelist unique constraint

Revision ID: 7155d97aeebd
Revises: 68888cf540ab
Create Date: 2026-03-07 16:56:02.702222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7155d97aeebd'
down_revision: Union[str, None] = '68888cf540ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('proposal_whitelists_agent_wallet_key'), 'proposal_whitelists', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('proposal_whitelists_agent_wallet_key'), 'proposal_whitelists', ['agent_wallet'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
