"""add agent actions

Revision ID: 87bb6dc0f6d0
Revises: ea0f6a28bb1f
Create Date: 2026-03-07 16:04:22.372869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bb6dc0f6d0'
down_revision: Union[str, None] = 'ea0f6a28bb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
