"""fix whitelist unique constraint

Revision ID: a6cfadbc4e33
Revises: 7155d97aeebd
Create Date: 2026-03-08 04:39:53.101472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cfadbc4e33'
down_revision: Union[str, None] = '7155d97aeebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
