"""fix agent_id type a

Revision ID: b8da6a4cf3f9
Revises: feaf9e42a509
Create Date: 2026-03-09 15:43:18.211471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8da6a4cf3f9'
down_revision: Union[str, None] = 'feaf9e42a509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
