"""update onchain

Revision ID: bc27ec9c5975
Revises: 5dfa7ecbd47f
Create Date: 2026-03-11 16:21:42.092719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc27ec9c5975'
down_revision: Union[str, None] = '5dfa7ecbd47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
