"""add balance data bnb

Revision ID: eef1c2df5272
Revises: d53c2eb234d4
Create Date: 2026-03-09 13:56:31.096850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef1c2df5272'
down_revision: Union[str, None] = 'd53c2eb234d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_snapshots', sa.Column('bnb_value_usd', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_snapshots', 'bnb_value_usd')
    # ### end Alembic commands ###
